Thatched/urls.py
from django.conf.urls import patterns, include, url 
from account.views import *
from article.views import *
from editor.views import *

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Thatched.views.home', name='home'),
    # url(r'^Thatched/', include('Thatched.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
	#url(r'^tinymce/',include('tinymce.urls')),
	(r'^ckeditor/', include('ckeditor.urls')),
)

urlpatterns += patterns('article.views',
	(r'^$|^index/$', index),
	(r'^writting/$', LoginRequired(writeblog)),
	(r'^leaves/$|^leaves/(\d{1,8})/$', leaves),
	(r'^getleaves/$', getleaves),
	(r'^getclassform/$', getclassform),
	(r'^gettagsform/$', gettagsform),
)

urlpatterns += patterns('editor.views',
	(r'editor/$', editor_main),
)

urlpatterns += patterns('account.views',
	(r'^login/$', login),
	(r'^logout/$', LoginRequired(logout)),
	(r'^profile/$|^profile/(\d{1,8})/$', LoginRequired(profile)),
)

urlpatterns += patterns('account.functions',
	(r'^getpic/$', GetPic),
)

article/models.py
#-*- coding=utf-8 -*-
from django.db import models
from account.models import *

# Create your models here.

class Tag(models.Model):
	tagid			= models.AutoField(primary_key=True)
	tagname			= models.CharField(max_length=16)
	def __unicode__(self):
		return self.tagname
	def toURL(self):
		return self.tagname.replace(r'+', r'%2B')
	@staticmethod
	def sort_by_number_of_articles():
		def cmpkey(opt):
			return opt.article_set.count()
		tags = Tag.objects.all()
		return sorted(tags, reverse=True, key=cmpkey)

class Classification(models.Model):
	classid			= models.AutoField(primary_key=True)
	creator			= models.ForeignKey(User)
	classname		= models.CharField(max_length=16)
	def __unicode__(self):
		return self.classname

class Article(models.Model):
	articleid		= models.AutoField(primary_key=True)
	visit			= models.IntegerField(default=0)
	tags			= models.ManyToManyField(Tag, null=True)
	title			= models.CharField(max_length=256)
	subtitle		= models.CharField(max_length=526)
	classification	= models.ForeignKey(Classification)
	author			= models.ForeignKey(User)
	postime			= models.DateTimeField()
	modifytime		= models.DateTimeField()
	content			= models.TextField(max_length=32767)
	class Meta:
		ordering	= ['-postime']
	def tagselector(self):
		return [(x.tagid, x.tagname) for x in self.tags.all()]

article/forms.py
#-*- coding=utf-8 -*-
from django import forms
from article.models import *
#from ckeditor.widgets import CKEditor
from ckeditor.widgets import CKEditorWidget
#from tinymce import models as tinymce_models


class BlogPostForm(forms.ModelForm):
	classid			= forms.ChoiceField(label="Classification")
	subtitle		= forms.CharField(required=False, widget=forms.TextInput(attrs={
			'placeholder':	'SubTitle',
		}))
	class Meta:
		model = Article
		fields = ('title', 'subtitle', 'content')
		widgets = {
			'title':	forms.TextInput(attrs={'placeholder':'Title'}),
			'content':	CKEditorWidget(),
			'subtitle':	forms.TextInput(attrs={'placeholder':'SubTitle'})
		}
	#subtitle = forms.CharField(widget=CKEditorWidget(config_name='none_toolbar'))
	#subtitle = forms.CharField()
	#tags			= forms.CharField(widget=CKEditorWidget(config_name='none_toolbar'))

article/views.py
#-*- coding=utf-8 -*-
from account.functions import *
from article.forms import *
# Create your views here.

def index(request):
	loginuser = LoginUser(request)
	return render_to_response('article/index.html', {
		'loginuser': loginuser,
	},context_instance=RequestContext(request))

def writeblog(request):
	loginuser = LoginUser(request)
	errors = []
	form = BlogPostForm()
	form.base_fields['classid'].choices = loginuser.classelector()
	form.fields['classid'].choices = loginuser.classelector()
	command = "create"
	if request.method == "POST":
		form = BlogPostForm(request.POST)
		a = form.fields
		if form.is_valid():
			title		= form.cleaned_data['title']
			subtitle	= form.cleaned_data['subtitle']
			content		= form.cleaned_data['content']
			classid		= int(form.cleaned_data['classid'])
			articleid	= request.POST.get('articleid', '')
			command		= request.POST.get('command', '')
			if articleid and command == "modify":
				try:
					article = Article.objects.get(articleid=articleid)
				except Article.DoesNotExist:
					errors.append(u'article does not exist.')
				else:
					if article.author != loginuser:
						errors.append(u'you can\'t edit the article post by others.')
					else:
						article.title			= title
						article.subtitle		= subtitle
						article.content			= content
						article.classification	= Classification.objects.get(classid=classid)
						article.modifytime		= datetime.datetime.utcnow().replace(tzinfo=pytz.utc)
						article.save()
						return HttpResponseRedirect("/leaves/%d/" % (article.articleid))
			elif command == "create":
				article = Article.objects.create(
						title			= title,
						subtitle		= subtitle,
						content			= content,
						author			= loginuser,
						classification	= Classification.objects.get(classid=classid),
						postime			= datetime.datetime.utcnow().replace(tzinfo=pytz.utc),
						modifytime		= datetime.datetime.utcnow().replace(tzinfo=pytz.utc),
				)
				return HttpResponseRedirect("/leaves/%d/" % (article.articleid))
	return render_to_response('article/writeblog.html', {
		'errors':		errors,
		'loginuser':	loginuser,
		'form':			form,	
		'command':		command,
	},context_instance=RequestContext(request))

def leaves(request, articleid=0):
	loginuser		= LoginUser(request)
	errors			= []
	tagname			= request.GET.get('tagname', '')
	tag				= ""
	if tagname:
		try:
			tag = Tag.objects.get(tagname=u"%s" % (tagname))
		except Tag.DoesNotExist:
			errors.append(u"tag does not exist.")
	if articleid:
		try:
			article = Article.objects.get(articleid=articleid)
		except Article.DoesNotExist:
			errors.append(u'Article Not Found')
		else:
			article.visit += 1
			article.save()
			if loginuser:
				form = BlogPostForm(initial={
					'classid':		loginuser.classelector(),
					'title':		article.title,
					'subtitle':		article.subtitle,
					'content':		article.content,
				})
				form.base_fields['classid'].choices = loginuser.classelector()
				form.fields['classid'].choices = loginuser.classelector()
			else:
				form = BlogPostForm()
			return render_to_response('article/leaves_specific.html', {
				'errors':		errors,
				'loginuser':	loginuser,
				'article':		article,
				'form':			form,
			},context_instance=RequestContext(request))
	return render_to_response('article/leaves.html', {
		'errors':		errors,
		'loginuser':	loginuser,
		'tag':			tag,
		'tags':			Tag.sort_by_number_of_articles()[0:10],
	},context_instance=RequestContext(request))

def getleaves(request):
	errors = []
	if request.method == "GET":
		command	= request.GET.get('command', '')
		number	= request.GET.get('number', '1')
		page	= request.GET.get('page', '1')
		uid		= request.GET.get('uid', '1')
		tagname	= request.GET.get('tagname', '')
		number	= int(number)
		page	= int(page)
		uid		= int(uid)
		if command == "newest":
			items = Article.objects.all()
		elif command == "userleaves":
			try:
				user	= User.objects.get(uid=uid)
			except User.DoesNotExist:
				errors.append(u'user does not exist.')
			else:
				items = user.article_set.all()
		elif command == "tagleaves":
			if tagname:
				try:
					tag = Tag.objects.get(tagname=tagname)
				except Tag.DoesNotExist:
					errors.append(u"tag does not exist.")
					items = Article.objects.all()
				else:
					items = tag.article_set.all()
			else:
				item = Article.objects.all()
		if number <= 0:
			number = 1
		if (page - 1) * number > items.count() - 1:
			page = 1;
		if (page - 1) * number < 0:
			page = (items.count() - 1) / number + 1
	return render_to_response('article/getleaves.html', {
		'items':	items[number * (page - 1):number * page],
		'page':		page,
	},context_instance=RequestContext(request))

def getclassform(request):
	errors = []
	msgs = []
	classifies = []
	loginuser = LoginUser(request)
	if request.method == "GET":
		formname = request.GET.get('form_name', '')
	if request.method == "POST":
		formname	= request.POST.get('form_name', '')
		classname	= request.POST.get('classname', '')
		classid		= request.POST.get('classid', '')
		articleid	= request.POST.get('articleid', '')
		classifies	= request.POST.getlist('classifies[]', [])
		if formname == "create":
			if CharValid(classname) and classname != "unclassified" and classname != "":
				Classification.objects.create(
					creator		= loginuser,
					classname	= classname,
				)
				msgs.append(u'classification create successfuly.')
			else:
				errors.append(u'classname invalid.')
		elif formname == "moveto":
			if articleid:
				try:
					article = Article.objects.get(articleid=articleid)
				except Article.DoesNotExist:
					errors.append(u'article does not exist.')
				else:
					if article.author != loginuser:
						errors.append(u'you can\'t edit the article post by others.')
					else:
						try:
							article.classification = Classification.objects.get(classid=classid)
						except Classification.DoesNotExist:
							errors.append(u'class does not exist.')
						else:
							article.save()
							msgs.append(u'classification change successfuly.')
			else:
				errors.append(u'article not found.')
		elif formname == "delete":
			for classid in classifies:
				try:
					classification = Classification.objects.get(classid=classid)
				except Classification.DoesNotExist:
					errors.append(u'classification %s does no exist.' % (classid))
				else:
					if classification.creator == loginuser and classification.classname != "unclassified":
						for art in classification.article_set.all():
							art.classification = loginuser.classification_set.get(classname="unclassified")
							art.save()
						classification.delete()
						msgs.append(u'delete successfuly.')
					else:
						errors.append(u'you can\'t delete the classification created by others or delete the default classification.')
	return render_to_response('article/classform.html', {
		'errors':				errors,
		'msgs':					msgs,
		'loginuser':			loginuser,
		'formname':				formname,
		'classifies':			classifies,
	},context_instance=RequestContext(request))

def gettagsform(request):
	errors = []
	msgs = []
	tags = []
	loginuser = LoginUser(request)
	article = ""
	if request.method == "GET":
		formname = request.GET.get('form_name', '')
		articleid = request.GET.get('articleid', '1')
		try:
			article = Article.objects.get(articleid=articleid)
		except Article.DoesNotExist:
			errors.append(u"article does not exist.")
	if request.method == "POST":
		formname	= request.POST.get('form_name', '')
		tagname		= request.POST.get('tagname', '')
		tagid		= request.POST.get('tagid', '')
		articleid	= request.POST.get('articleid', '')
		tags		= request.POST.getlist('tags[]', [])
		if formname == "add":
			if CharValid(tagname):
				tag = Tag.objects.get_or_create(
					tagname	= tagname,
				)
				try:
					article = Article.objects.get(articleid=articleid)
				except Article.DoesNotExist:
					errors.append(u"article does not exist.")
				else:
					article.tags.add(tag[0])
					msgs.append(u'tag create successfuly.')
			else:
				errors.append(u'tagname invalid.')
		elif formname == "edt":
			try:
				article = Article.objects.get(articleid=articleid)
			except Article.DoesNotExist:
				errors.append(u"article does not exist.")
			else:
				article.tags.clear()
				for tagid in tags:
					try:
						tag = Tag.objects.get(tagid=tagid)
					except Tag.DoesNotExist:
						errors.append(u'tag %s does no exist.' % (tagname))
					else:
						article.tags.add(tag)
				msgs.append(u"edit successfuly.")
	return render_to_response('article/tagsform.html', {
		'errors':				errors,
		'msgs':					msgs,
		'loginuser':			loginuser,
		'formname':				formname,
		'article':				article,
	},context_instance=RequestContext(request))

templates/article/classform.html
{% if errors %}
<ul class="errorlist">
	{% for error in errors %}
	<li>{{ error }}</li>
	{% endfor %}
</ul>
<input id="flag" value="0" style="display:none"></input>
{% else %}
<ul class="msglist">
	{% for msg in msgs %}
	<li>{{ msg }}</li>
	{% endfor %}
</ul>
<input id="flag" value="1" style="display:none"></input>
{% endif %}
{% if formname == "moveto" %}
<select name="classify" id="id_classify">
	{% for opt in loginuser.classelector %}
	<option value="{{ opt.0 }}">{{ opt.1 }}</option>
	{% endfor %}
</select>
{% else %}
{% if formname == "create" %}
<input name="classname" id="id_classname"/>
{% else %}
{% if formname == "delete" %}
{% for opt in loginuser.classelector %}
<input type="checkbox" name="checklist" value="{{ opt.0 }}">{{ opt.1 }}</input>
{% endfor %}
{% endif %}
{% endif %}
{% endif %}

templates/article/getleaves.html
{% load filters %}
<input id="currpage" type="hidden" name="page" value="{{page}}">
<ul class="leaves_list">
	{% for item in items %}
	<li class="list-item">
	<div class="leaves_head">
		<a class="title" href="/leaves/{{ item.articleid }}/">{{ item.title|title }}</a>
		<a class="datetime" >{{ item.postime|date }}</a>
		<a class="author" href="/profile/{{ item.author.uid}}/">@{{ item.author.profile.nickname }}</a>
	</div>
	<div class="leaves_content">
		<!-- <a class="" href="/leaves/{{ item.articleid }}/">{{ item.content|striptags|cut:"&nbsp;"|center:"1"|truncatewords:"30"|escape }}</a> -->
		<a class="" href="/leaves/{{ item.articleid }}/">{{ item.content|striptags|cut:"&nbsp;"|center:"1"|truncatehanzi:"20"|escape }}</a>
	</div>
	</li>
	{% endfor %}
</ul>

templates/article/index.html
{% extends "basic.html" %}
{% block header_ext %}
<head><meta charset="utf-8"/></head>
{% endblock %}
{% block body %}
<article class="">
</article>
{% endblock %}

templates/article/leaves_specific.html
{% extends "basic.html" %}
{% block head_ext %}
<style>
	.leaves_panel {
		margin-left:			auto;
		margin-right:			auto;
		margin-bottom:			30px;
		padding:				50px 0px 0px 0px;
		width:					95%;
		height:					100%;
		min-height:				839px;
		background-color:		rgba(39,39,39,0.9);
		box-shadow:				10px 10px 10px rgba(155,155,155,1.0);
		background-clip:		content-box;
	}
	.leaves_panel .leaf {
		margin-top:				20px;
		margin-left:			auto;
		margin-right:			auto;
		margin-bottom:			15px;
		padding:				2%;
		background-color:		rgba(255,255,255,1.0);
		border-radius:			3px;
		box-shadow:				5px 5px 5px rgba(155,155,155,0.6);
		min-width:				600px;
		width:					90%;
		height:					100%;
	}
	.toolbar_menu {
		width:					100%;
	}
	.toolbar_menu a {
		cursor:					default;
	}
	.forms {
		width:					100%;
		height:					100%;
	}
	.article {
		position:				relative;
	}
	.writting {
		position:				relative;
	}
	@keyframes form_leave {
		0%							{opacity:1;display:block;transform:scale(1.0);}
		100%						{opacity:0;display:none;transform:scale(0.0);}
	}
	@-moz-keyframes form_leave {
		0%							{opacity:1;display:block;-moz-transform:scale(1.0);}
		100%						{opacity:0;display:none;-moz-transform:scale(0.0);}
	}
	@-webkit-keyframes form_leave {
		0%							{opacity:1;display:block;-webkit-transform:scale(1.0);}
		100%						{opacity:0;display:none;-webkit-transform:scale(0.0);}
	}
	@-o-keyframes form_leave {
		0%							{opacity:1;display:block;-o-transform:scale(1.0);}
		100%						{opacity:0;display:none;-o-transform:scale(0.0);}
	}
	@-moz-keyframes form_come {
		0%							{opacity:0;display:none;-moz-transform:scale(0.0);}
		100%						{opacity:1;display:block;-moz-transform:scale(1.0);}
	}
	@-webkit-keyframes form_come {
		0%							{opacity:0;display:none;-webkit-transform:scale(0.0);}
		100%						{opacity:1;display:block;-webkit-transform:scale(1.0);}
	}
	@-o-keyframes form_come {
		0%							{opacity:0;display:none;-o-transform:scale(0.0);}
		100%						{opacity:1;display:block;-o-transform:scale(1.0);}
	}
	.leaving {
		animation:					form_leave 1s linear 0s 1 normal;
		-webkit-animation:			form_leave 1s linear 0s 1 normal;
		-moz-animation:				form_leave 1s linear 0s 1 normal;
		-o-animation:				form_leave 1s linear 0s 1 normal;
		display:					none;
	}
	.comming {
		animation:					form_come 1s linear 0s 1 normal;
		-webkit-animation:			form_come 1s linear 0s 1 normal;
		-moz-animation:				form_come 1s linear 0s 1 normal;
		-o-animation:				form_come 1s linear 0s 1 normal;
		display:					block;
	}
</style>
<script type="text/javascript" src="/static/js/csrf.js"></script>
<script>
	function edit_or_show () {
		var command=$("#edit").html();
		if (command == "edit") {
			$("#edit").html("cancel");
			$("#article").removeClass("comming leaving").delay(100).queue(function(next){
				$(this).addClass("leaving");
				next();
			});
			$("#writting").removeClass("coming").delay(100).queue(function(next){
				$(this).addClass("comming");
				next();
			});
		}
		else {
			$("#edit").html("edit");
			$("#writting").removeClass("comming leaving").delay(100).queue(function(next){
				$(this).addClass("leaving");
				next();
			});
			$("#article").removeClass("coming").delay(100).queue(function(next){
				$(this).addClass("comming");
				next();
			});
		}
	}
	function getclassform(name, method) {
		var url = "/getclassform/"
		if (method == "get") {
			$.get(url, {'form_name':name}, function(data) {
				if (name == 'create') {
					$("#classform_create").html(data);
					$("#classform_create").dialog("open");
				}
				if (name == 'moveto') {
					$("#classform_moveto").html(data);
					$("#classform_moveto").dialog("open");
				}
				if (name == 'delete') {
					$("#classform_delete").html(data);
					$("#classform_delete").dialog("open");
				}
			});
		}
		else if (method == "post") {
			var classid = $("#id_classify").val();
			var classname = $("#id_classname").val();
			var articleid = $("#articleid").val();
			var classifies = [];
			var checklist = $("[name=checklist][type=checkbox]:checked")
			checklist.each(function(){classifies.push($(this).val());});
			$.post(url, {'form_name':name, 'classid':classid, 'classname':classname, 'articleid':articleid, 'classifies[]':classifies}, function(data) {
				if (name == "create") {
					$("#classform_create").html(data);
					$("#classform_create").dialog("open");
					refreshPage(location.href);
				}
				if (name == "moveto") {
					$("#classform_moveto").html(data);
					$("#classform_moveto").dialog("open");
					refreshPage(location.href);
				}
				if (name == "delete") {
					$("#classform_delete").html(data);
					$("#classform_delete").dialog("open");
					refreshPage(location.href);
				}
			});
		}
	}
	function gettagsform(name, method) {
		var url = "/gettagsform/";
		var articleid = $("#articleid").val();
		if (method == "get") {
			$.get(url, {'form_name':name, 'articleid':articleid}, function(data) {
				if (name == 'add') {
					$("#tagsform_add").html(data);
					$("#tagsform_add").dialog("open");
				}
				if (name == 'edt') {
					$("#tagsform_edt").html(data);
					$("#tagsform_edt").dialog("open");
				}
			});
		}
		else if (method == "post") {
			var tagid = $("#id_tag").val();
			var tagname = $("#id_tagname").val();
			var articleid = $("#articleid").val();
			var tags = [];
			var checklist = $("[name=checklist][type=checkbox]:checked")
			checklist.each(function(){tags.push($(this).val());});
			$.post(url, {'form_name':name, 'tagsid':tagid, 'tagname':tagname, 'articleid':articleid, 'tags[]':tags}, function(data) {
				if (name == "add") {
					$("#tagsform_add").html(data);
					$("#tagsform_add").dialog("open");
					refreshPage(location.href);
				}
				if (name == "edt") {
					$("#tagsform_edt").html(data);
					$("#tagsform_edt").dialog("open");
					refreshPage(location.href);
				}
			});
		}
	}
	var refreshPage = function(url) {
		var flag = $("#flag").val();
		if (flag == 1) {
			setTimeout("window.location.assign('" + url + "')", 500);
		}
	}
	function handler() {
		$("#class_create").click(function() {getclassform('create', 'get')});
		$("#class_moveto").click(function() {getclassform('moveto', 'get')});
		$("#class_delete").click(function() {getclassform('delete', 'get')});
		$("#tags_add").click(function() {gettagsform('add', 'get')});
		$("#tags_edt").click(function() {gettagsform('edt', 'get')});
		$("#classform_create").dialog({
			autoOpen: false,
			modal:true,
			resizable:false,
			buttons:{
				"create":function() {
					getclassform('create', 'post');
				},
				"cancle":function() {
					$(this).dialog("close");
				}
			},
			close: function() {
				$("#classform_create").empty()
			}
		});
		$("#classform_moveto").dialog({
			autoOpen: false,
			modal:true,
			resizable:false,
			buttons:{
				"moveto":function() {
					getclassform('moveto', 'post');
				},
				"cancle":function() {
					$(this).dialog("close");
				}
			},
			close: function() {
				$("#classform_moveto").empty()
			}
		});
		$("#classform_delete").dialog({
			autoOpen: false,
			modal:true,
			resizable:false,
			buttons:{
				"delete":function() {
					getclassform('delete', 'post');
				},
				"cancle":function() {
					$(this).dialog("close");
				}
			},
			close: function() {
				$("#classform_delete").empty()
			}
		});
		$("#tagsform_add").dialog({
			autoOpen: false,
			modal:true,
			resizable:false,
			buttons:{
				"add":function() {
					gettagsform('add', 'post');
				},
				"cancle":function() {
					$(this).dialog("close");
				}
			},
			close: function() {
				$("#tagsform_add").empty()
			}
		});
		$("#tagsform_edt").dialog({
			autoOpen: false,
			modal:true,
			resizable:false,
			buttons:{
				"edit":function() {
					gettagsform('edt', 'post');
				},
				"cancle":function() {
					$(this).dialog("close");
				}
			},
			close: function() {
				$("#tagsform_edt").empty()
			}
		});
	}
	$(document).ready(handler);
</script>
<link rel="stylesheet" type="text/css" href="/static/css/article/writting.css">
<script type="text/javascript" src="/static/ckeditor/ckeditor/ckeditor.js"></script>
{% endblock %}
{% block body %}
<div class="leaves_panel">
	<div class="leaf">
		<div class="content">
			{% if article in loginuser.article_set.all %}
			<div class="toolbar">
				<ul class="toolbar_menu">
					<li class="edit" onclick="edit_or_show()"><a id="edit" name="edit">edit</a></li>
					<li class="classifylist">
					<a id="classify" name="classify">classification</a>
					<ul class="">
						<li id="class_moveto"><a>move to</a></li>
						<li id="class_create"><a>create new</a></li>
						<li id="class_delete"><a>delete</a></li>
					</ul>
					</li>
					<li class="tagslist">
					<a id="tags" name="tags">tags</a>
					<ul class="">
						<li id="tags_add"><a>add new tag</a></li>
						<li id="tags_edt"><a>edit tags</a></li>
					</ul>
					</li>
				</ul>
			</div>
			{% endif %}
			<div class="forms">
				<div id="article" class="article comming">
					<article>
						<a href="/leaves/{{ article.articleid }}/"><h2>{{ article.title|title }}</h2></a>
						<h3 id="subtitle">{{ article.subtitle }}</h3>
						<p>tags:
						{% for tag in article.tags.all %}
						&nbsp;<a href="/leaves/?tagname={{ tag.tagname }}">{{ tag.tagname }}</a>
						{% endfor %}
						</p>
						<p id="classification">Classification:{{ article.classification }} | visit:{{ article.visit }}</p>
						Author:{{ article.author }} | Date:{{ article.postime }} | Lastupdate:{{ article.modifytime }}
					</article>
					<div class="">
						{% autoescape off %}
						{{ article.content }}
						{% endautoescape %}
					</div>
				</div>
				{% if article in loginuser.article_set.all %}
				<div id="writting" class="writting leaving">
					<form class="write_form" id="id_blogform" action="/writting/" method="post">
						{% csrf_token %}
						<div class="title">
							{{ form.title }}
							{{ form.title.errors }}
						</div>
						<div class="subtitle">
							{{ form.subtitle }}
						</div>
						<div class="content">
							{% autoescape off %}
							{{ form.content }}
							{% endautoescape %}
						</div>
						<div class="classid">
							{{ form.classid }}
						</div>
						<div class="submit">
							<input id="articleid" type="hidden" name="articleid" value="{{ article.articleid }}">
							<input id="command" type="hidden" name="command" value="modify">
							<input class="" type="submit" value="post">
						</div>
					</form>
				</div>
				<div id="classform_create">
				</div>
				<div id="classform_moveto">
				</div>
				<div id="classform_delete">
				</div>
				<div id="tagsform_add">
				</div>
				<div id="tagsform_edt">
				</div>
				{% endif %}
			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/article/tagsform.html
{% if errors %}
<ul class="errorlist">
	{% for error in errors %}
	<li>{{ error }}</li>
	{% endfor %}
</ul>
<input id="flag" value="0" style="display:none"></input>
{% else %}
<ul class="msglist">
	{% for msg in msgs %}
	<li>{{ msg }}</li>
	{% endfor %}
</ul>
<input id="flag" value="1" style="display:none"></input>
{% endif %}
{% if formname == "add" %}
<input name="tagname" id="id_tagname"/>
{% else %}
{% if formname == "edt" %}
{% for opt in article.tagselector %}
<input type="checkbox" name="checklist" value="{{ opt.0 }}" checked>{{ opt.1 }}</input>
{% endfor %}
{% endif %}
{% endif %}

templates/article/writeblog.html
{% extends "basic.html" %}
{% block title %}Writting{% endblock %}
{% block head_ext %}
<link rel="stylesheet" type="text/css" href="/static/css/article/writting.css">
<script type="text/javascript" src="/static/ckeditor/ckeditor/ckeditor.js"></script>
{% endblock %}
{% block body %}
<div class="write_panel">
	<ul class="errorlist">
		{% for error in errors %}
		<li>{{ error }}</li>
		{% endfor %}
	</ul>
	<form class="write_form" id="id_blogform" action="" method="post">
		{% csrf_token %}
		<div class="title">
			{{ form.title }}
			{{ form.title.errors }}
		</div>
		<div class="subtitle">
			{{ form.subtitle }}
		</div>
		<div class="content">
			{% autoescape off %}
			{{ form.content }}
			{% endautoescape %}
		</div>
		<div class="classid">
			{{ form.classid }}
		</div>
		<div class="submit">
			<input type="hidden" name="command" value="{{ command }}">
			<input class="" type="submit" value="post">
		</div>
	</form>
<!-- <textarea style="padding:40px;width:800px;height:500px;" class="ckeditor" rows="90" cols="60" name="blogcontent"  ></textarea> -->
</div>
{% endblock %}